spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/biblioteca
    username: andrea
    password: italiano
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    hbm2ddl:
      auto: update
server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.data.jpa: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE